<a href="https://colab.research.google.com/github/Saketbishnu/AI-ML-Journey/blob/main/Deep_learning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
#implementation of neural networks
import torch
import torch.nn as nn

In [22]:
#input
#to get exact output we can use {torch.manual_seed(42)}
inputs = torch.tensor([1.0, 2.0, 3.0])

In [23]:
neuron = nn.Linear(in_features=3, out_features=1)

In [24]:
output = neuron(inputs)

In [25]:
output

tensor([1.1157], grad_fn=<ViewBackward0>)

In [26]:
#verify formula
neuron.weight @ inputs

tensor([1.2473], grad_fn=<MvBackward0>)

In [27]:
neuron.weight

Parameter containing:
tensor([[ 0.2896, -0.2835,  0.5082]], requires_grad=True)

In [28]:
neuron.bias

Parameter containing:
tensor([-0.1317], requires_grad=True)