<a href="https://colab.research.google.com/github/Saketbishnu/AI-ML-Journey/blob/main/Deep_learning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#implementation of neural networks
import torch
import torch.nn as nn

In [2]:
#input
#to get exact output we can use {torch.manual_seed(42)}
inputs = torch.tensor([1.0, 2.0, 3.0])

In [3]:
neuron = nn.Linear(in_features=3, out_features=1)

In [4]:
output = neuron(inputs)

In [5]:
output

tensor([0.8998], grad_fn=<ViewBackward0>)

In [6]:
#verify formula
neuron.weight @ inputs

tensor([0.3624], grad_fn=<MvBackward0>)

In [7]:
neuron.weight

Parameter containing:
tensor([[-0.3339, -0.3990,  0.4981]], requires_grad=True)

In [8]:
neuron.bias

Parameter containing:
tensor([0.5375], requires_grad=True)