In [1]:
#implementaion of neural network
import torch
import torch.nn as nn

In [5]:
#to get exact output we can use {torch.manual_seed(42)}
inputs = torch.tensor([1.0, 2.0, 3.0])

In [6]:
neuron = nn.Linear(in_features=3, out_features=1)

In [7]:
output=neuron(inputs)

In [8]:
output

tensor([-1.6801], grad_fn=<ViewBackward0>)

In [9]:
neuron.weight

Parameter containing:
tensor([[-0.0446, -0.4314, -0.0674]], requires_grad=True)

In [10]:
neuron.bias

Parameter containing:
tensor([-0.5704], requires_grad=True)

In [11]:
#verify formula
neuron.weight @ inputs + neuron.bias

tensor([-1.6801], grad_fn=<AddBackward0>)