In [2]:
#data types
import numpy as np

In [8]:
arr1 = np.array([3+5j])
arr2 = np.array([5+3j])

print(arr1+arr2)

[8.+8.j]


In [26]:
#multi-dimensional array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns =np.sum(arr2D,axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)

#To access any particular ais number
print(arr2D[0:2, 1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [43]:
#Example of an 3D array
arr3D = np.array([[[1,2], [3,4],[5,6]], [[7,8],[9,10],[11,12]]])
print(arr3D, arr3D.shape)
#indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])

#slicing
print(arr3D[:, 0, :])#first row from both layper
print(arr3D[:,:,0])# first col from the layer

arr3D[:,0,:] =99 #first row from both layer
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [46]:
#vectorization
arr = np.array([1,2,3,4,5])
print(arr **2)

[ 1  4  9 16 25]


In [54]:
#broadcasting
arr = np.array([1,2,3,4,5])
arr2 =np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr +arr2)

[[ 2  4  6  8 10]
 [ 3  5  7  9 11]]


In [10]:
#normalization
arr =np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895
