In [2]:
import numpy as np

In [34]:
arr = np.array([1,2,3,4,5])

In [35]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [10]:
import numpy as np
import time

# execution performance
size = 10_000_000

# python list
py_list = list(range(size))
start = time.time()
sq_list = [x ** 2 for x in py_list]
end = time.time()
print(f"python list time = {end - start} seconds")

# numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end - start} seconds")


python list time = 0.8002719879150391 seconds
numpy array time = 0.009000301361083984 seconds


In [11]:
#memeory
import sys
print(f"python list size ={sys.getsizeof(py_list)* len(py_list)} bytes")

print(f"numpy array size ={np_arr.nbytes} bytes")


python list size =800000560000000 bytes
numpy array size =40000000 bytes


In [12]:
#create - from lists
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])# int is converted into string
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [14]:
#different function to create an np array

In [15]:
#create
arr1 = np.zeros((2, 3), dtype="int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [16]:
#properties of numpy array

In [17]:
arr = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [39]:
#reshapping the array

In [6]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened =arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [22]:
#indexing

arr= np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])

arr= np.array([[1,2,3],[4,5,6]])
print(arr[0][0])


1
4
1


In [28]:
# Fancy indexing
arr =np.array([1,2,3,4,5])

idx =[0,1,3]
print(arr[idx])

[1 2 4]


In [34]:
#boolean indexing
print(arr[arr > 2])
print(arr[arr % 2 ==0])
print(arr[arr % 2 !=0])

[3 4 5]
[2 4]
[1 3 5]


In [40]:
#slicing
#[start, end, step]
print(arr[1:4])
print(arr[1:])
print(arr[:3])
print(arr[::2])



[2 3 4]
[2 3 4 5]
[1 2 3]
[1 3 5]


In [52]:
#python list form copy and numpy list form a view 
#i.e is one of the reason that numpy array is faster tha lists
nums =[1,2,3,4,]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] =200
print(sub_list)
print(nums)


[2, 3]
[200, 3]
[1, 2, 3, 4]


In [9]:
#view in numpyarray
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] =200
print(sub_arr)
print(arr)

print(arr[1])

[2 3]
[200   3]
[  1 200   3   4   5]
200
